version: "3.4"

services:
  site:
    build:
      context: .
      target: php_dev
    ports:
      - "8000:80"
    volumes:
      - ./www/:/var/www/html/

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=boissons
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

